language: python

matrix:
  include:
    - python: 3.5
      env:
        - FREETYPE=""
        - COVERAGE=false
        - ARGS=""
    - python: 3.6
      env:
        - FREETYPE=""
        - COVERAGE=true
        - ARGS=""
    - python: 3.6
      env:
        - FREETYPE="freetype=2.7"
        - COVERAGE=true
        - ARGS="--mpl --pep8 --cov"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda create --yes --channel=conda-forge --name=test python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib statsmodels seaborn mpl-probscale pytest pytest-cov pytest-mpl pytest-pep8 coverage docopt requests pyyaml $FREETYPE
  - source activate test
  - pip install codecov
  - pip install .

script:
  - python check_wqio.py ${ARGS}

after_success:
  - if [ ${COVERAGE} = true ]; then
      coverage report -m;
      codecov;
    fi

