language: python

matrix:
  fast_finish: true
  include:    
    - python: 3.8

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda create --name=test python=$TRAVIS_PYTHON_VERSION nomkl --channel=conda-forge --yes
  - source activate test
  - conda install numpy scipy pandas matplotlib statsmodels seaborn mpl-probscale pytest pytest-cov pytest-mpl pytest-pep8 coverage docopt requests pyyaml tqdm --channel=conda-forge --yes
  - pip install codecov
  - pip install .
  - conda list

script:
  - coverage run --source wqio check_wqio.py --strict --verbose

after_success:
  - coverage report -m;
  - codecov;
